#!/bin/bash
#SBATCH --job-name=Amber_Apo_6ONI_Run
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --mem=40G
#SBATCH --time=5-00:00:00
#SBATCH --partition=batch_gpu
#SBATCH --account=csb_gpu_acc
#SBATCH --gres=gpu:nvidia_titan_x:1   # request exactly 3 GPUs on this node
#SBATCH --output=PPARg_meta_out_%j.log
#SBATCH --error=PPARg_meta_err_%j.log

module purge
module load StdEnvACCRE/2023
module load gcc/12.3 openmpi/4.1.5 cuda/12.2
module load ambertools/25.0
module load scipy-stack/2025a
module load amber/24
    
perl production.pl > PRODUCTION.OUT

